from __future__ import annotations

from pydantic import BaseModel, Field

from . import router
from ..blast_radius import compute_blast_radius
from ..diff_engine import cluster_changes, compute_diff_stats, parse_unified_diff
from ..schemas.gates import CoverageGate, IntakeGate
from ..schemas.input import GitHubPRData
from ..schemas.pipeline import (
    AdversaryResult,
    AnatomyResult,
    ChangeCluster,
    CrossRefInteraction,
    DiffStats,
    FileChange,
    IntakeResult,
    ReviewDimension,
    ReviewFinding,
    ReviewPlan,
    SubReviewRequest,
)


class _AnatomySemanticResult(BaseModel):
    pr_narrative: str = ""
    risk_surfaces: list[str] = Field(default_factory=list)
    unrelated_changes: list[str] = Field(default_factory=list)
    intent_gaps: list[str] = Field(default_factory=list)
    context_notes: str = ""


class _SubReviewRequest(BaseModel):
    reason: str = ""
    review_prompt: str = ""
    target_files: list[str] = Field(default_factory=list)
    context_files: list[str] = Field(default_factory=list)
    priority: int = 1


class _ReviewFindingsResult(BaseModel):
    findings: list[ReviewFinding] = Field(default_factory=list)
    sub_reviews: list[_SubReviewRequest] = Field(default_factory=list)


class _CrossRefResult(BaseModel):
    interactions: list[CrossRefInteraction] = Field(default_factory=list)


class _AdversaryPhaseResult(BaseModel):
    results: list[AdversaryResult] = Field(default_factory=list)


def _auto_depth(complexity: str) -> str:
    mapping = {
        "trivial": "quick",
        "standard": "standard",
        "complex": "deep",
        "massive": "deep",
    }
    return mapping.get(complexity, "standard")


def _language_from_path(path: str) -> str:
    ext_map = {
        ".py": "python",
        ".js": "javascript",
        ".jsx": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".rb": "ruby",
        ".php": "php",
        ".swift": "swift",
        ".kt": "kotlin",
        ".cs": "csharp",
        ".cpp": "cpp",
        ".c": "c",
        ".sql": "sql",
        ".html": "html",
        ".css": "css",
        ".md": "markdown",
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".sh": "bash",
    }
    for ext, language in ext_map.items():
        if path.endswith(ext):
            return language
    return ""


def _extract_languages(pr: GitHubPRData) -> list[str]:
    languages = {_language_from_path(changed.path) for changed in pr.changed_files if _language_from_path(changed.path)}
    return sorted(languages)


def _extract_areas(paths: list[str]) -> list[str]:
    area_patterns = {
        "auth": ("auth", "login", "oauth", "permission", "acl"),
        "database": ("db", "database", "migration", "schema", "model"),
        "api": ("api", "endpoint", "route", "controller", "handler"),
        "frontend": ("ui", "component", "view", "page", "css", "tsx", "jsx"),
        "tests": ("test", "spec", "fixture"),
        "ci": (".github", "workflow", "ci", "pipeline"),
        "config": ("config", "settings", ".env", "yaml", "toml", "json"),
        "infra": ("docker", "k8s", "terraform", "helm", "ansible"),
        "security": ("security", "crypto", "token", "jwt", "secret"),
    }
    lowered = [path.lower() for path in paths]
    detected: list[str] = []
    for area, patterns in area_patterns.items():
        if any(any(pattern in path for pattern in patterns) for path in lowered):
            detected.append(area)
    if not detected:
        detected.append("application")
    return detected


def _risk_signals(pr: GitHubPRData, areas_touched: list[str], files_changed: int) -> list[str]:
    signals: list[str] = []
    if "security" in areas_touched or "auth" in areas_touched:
        signals.append("touches authentication or security-sensitive paths")
    if "database" in areas_touched:
        signals.append("modifies data model or schema-affecting code")
    if "api" in areas_touched:
        signals.append("changes API surface or request/response behavior")
    if files_changed >= 25:
        signals.append("large change footprint across many files")
    if any(path.endswith((".yml", ".yaml", ".toml", ".json")) for path in (cf.path for cf in pr.changed_files)):
        signals.append("includes configuration changes")
    if any("test" in cf.path.lower() for cf in pr.changed_files):
        signals.append("test behavior updated")
    return signals


def _ai_generated_confidence(pr: GitHubPRData) -> float:
    signals = 0
    evidence = 0
    text_blobs = [pr.title, pr.description, *pr.commit_messages]
    patterns = (
        "generated by",
        "co-authored-by: claude",
        "co-authored-by: gpt",
        "ai-assisted",
        "autogenerated",
        "chatgpt",
        "copilot",
        "claude",
        "llm",
    )
    for blob in text_blobs:
        if not blob:
            continue
        evidence += 1
        lower = blob.lower()
        if any(pattern in lower for pattern in patterns):
            signals += 1
    if evidence == 0:
        return 0.0
    return min(1.0, signals / evidence)


def _pr_summary(pr: GitHubPRData) -> str:
    description = (pr.description or "").strip()
    if description:
        return description
    return f"{pr.title}. Files changed: {len(pr.changed_files)}."


def _file_changes_from_metadata(pr: GitHubPRData) -> list[FileChange]:
    return [
        FileChange(
            path=changed.path,
            status=changed.status,
            language=_language_from_path(changed.path),
            lines_added=changed.additions,
            lines_removed=changed.deletions,
            hunks=[],
        )
        for changed in pr.changed_files
    ]


def _cluster_descriptions(clusters: list[ChangeCluster]) -> list[dict[str, object]]:
    return [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "primary_language": cluster.primary_language,
            "files": cluster.files,
        }
        for cluster in clusters
    ]


@router.reasoner()
async def intake_phase(pr_data: dict, depth: str = "standard") -> dict:
    pr = GitHubPRData.model_validate(pr_data)
    files_changed = len(pr.changed_files)
    languages = _extract_languages(pr)
    import json as _json

    ai_input = _json.dumps(
        {
            "title": pr.title,
            "description": (pr.description or "")[:500],
            "labels": pr.labels,
            "author": pr.author,
            "files_changed": files_changed,
            "languages": languages,
            "commit_messages": pr.commit_messages[:5],
        },
        default=str,
    )

    gate_result = await router.app.ai(
        f"Classify this pull request from metadata and diff footprint.\n\n{ai_input}",
        system="Return pr_type, complexity, and confident only. Use the provided schema.",
        schema=IntakeGate,
    )

    if gate_result.confident:
        paths = [changed.path for changed in pr.changed_files]
        areas_touched = _extract_areas(paths)
        intake_result = IntakeResult(
            pr_type=gate_result.pr_type,
            complexity=gate_result.complexity,
            languages=languages,
            areas_touched=areas_touched,
            risk_signals=_risk_signals(pr, areas_touched, files_changed),
            ai_generated=_ai_generated_confidence(pr),
            review_depth=depth if depth != "auto" else _auto_depth(gate_result.complexity),
            pr_summary=_pr_summary(pr),
        )
        return intake_result.model_dump()

    fallback_input = _json.dumps(
        {
            "pr_title": pr.title,
            "description": (pr.description or "")[:1000],
            "requested_depth": depth,
            "languages": languages,
            "files_changed": files_changed,
        },
        default=str,
    )
    fallback_result = await router.app.harness(
        f"Perform deep intake classification for this pull request. "
        f"Infer PR type, complexity, touched areas, risk signals, AI-generation confidence, "
        f"and an accurate short PR summary for downstream reviewers.\n\n{fallback_input}",
        schema=IntakeResult,
    )
    return fallback_result.parsed.model_dump() if fallback_result.parsed else {}


@router.reasoner()
async def anatomy_phase(pr_data: dict, intake: dict, repo_path: str = "") -> dict:
    import json as _json

    pr = GitHubPRData.model_validate(pr_data)
    intake_result = IntakeResult.model_validate(intake)

    files = parse_unified_diff(pr.diff)
    if not files:
        files = _file_changes_from_metadata(pr)

    stats = compute_diff_stats(files)
    clusters = cluster_changes(files)
    changed_paths = [file.path for file in files]
    blast_radius = compute_blast_radius(changed_paths, repo_path)

    context = _json.dumps(
        {
            "intake": {
                "pr_type": intake_result.pr_type,
                "complexity": intake_result.complexity,
                "pr_summary": intake_result.pr_summary,
            },
            "pr_metadata": {"title": pr.title, "description": (pr.description or "")[:500], "labels": pr.labels},
            "clusters": _cluster_descriptions(clusters),
            "stats": stats.model_dump(),
            "blast_radius_count": len(blast_radius),
            "files_changed": [
                {"path": f.path, "status": f.status, "lines_added": f.lines_added, "lines_removed": f.lines_removed}
                for f in files[:30]
            ],
        },
        default=str,
    )
    semantic = await router.app.harness(
        f"Analyze the pull request semantically. Explain what changed and why, identify risk surfaces, "
        f"call out unrelated changes, and detect intent gaps between PR description and actual diff.\n\n{context}",
        schema=_AnatomySemanticResult,
        cwd=repo_path or None,
    )

    parsed = semantic.parsed if semantic.parsed else _AnatomySemanticResult()
    anatomy_result = AnatomyResult(
        files=files,
        clusters=clusters,
        blast_radius=blast_radius,
        dependency_graph={},
        stats=stats,
        pr_narrative=parsed.pr_narrative,
        risk_surfaces=parsed.risk_surfaces,
        unrelated_changes=parsed.unrelated_changes,
        intent_gaps=parsed.intent_gaps,
        context_notes=parsed.context_notes,
    )
    return anatomy_result.model_dump()


@router.reasoner()
async def planning_phase(intake: dict, anatomy: dict, depth: str = "standard", hints: list[str] | None = None) -> dict:
    import json as _json

    intake_result = IntakeResult.model_validate(intake)
    anatomy_result = AnatomyResult.model_validate(anatomy)
    planner_hints = hints or []

    context = _json.dumps(
        {
            "intake": {
                "pr_type": intake_result.pr_type,
                "complexity": intake_result.complexity,
                "pr_summary": intake_result.pr_summary,
                "areas_touched": intake_result.areas_touched,
                "risk_signals": intake_result.risk_signals,
            },
            "clusters": _cluster_descriptions(anatomy_result.clusters),
            "risk_surfaces": anatomy_result.risk_surfaces,
            "pr_narrative": anatomy_result.pr_narrative,
            "depth": depth,
            "hints": planner_hints,
            "file_paths": [f.path for f in anatomy_result.files[:30]],
        },
        default=str,
    )
    plan_result = await router.app.harness(
        f"Create a dynamic review plan for this PR. Do not use fixed reviewer templates. "
        f"Generate review dimensions based on intake and anatomy, with clear target files and context files. "
        f"Each dimension must include a concrete review_prompt that another reviewer can execute directly. "
        f"Balance depth with the requested review depth and prioritize highest-risk dimensions first.\n\n{context}",
        schema=ReviewPlan,
    )
    return plan_result.parsed.model_dump() if plan_result.parsed else {"dimensions": [], "cross_ref_hints": []}


@router.reasoner()
async def review_dimension(
    review_prompt: str,
    target_files: list[str],
    context_files: list[str] | None = None,
    repo_path: str = "",
    current_depth: int = 0,
    max_depth: int = 2,
) -> dict:
    ctx_files = context_files or []
    can_spawn = current_depth < max_depth

    spawn_instruction = ""
    if can_spawn:
        spawn_instruction = (
            "\n\nSUB-REVIEW SPAWNING: You may request deeper sub-reviews for areas that need "
            "specialized investigation beyond your current scope. Only request a sub-review when:\n"
            "- You found a complex issue that requires reading additional files not in your target list\n"
            "- A finding reveals a pattern that may repeat across other files\n"
            "- You suspect a security/correctness issue but lack context to confirm it\n"
            f"Current depth: {current_depth}/{max_depth}. "
            f"You have {max_depth - current_depth} level(s) of sub-review remaining. "
            "Do NOT request sub-reviews for trivial issues or things you can resolve yourself. "
            "Maximum 2 sub-reviews per dimension."
        )
    else:
        spawn_instruction = (
            "\n\nYou are at maximum review depth. Do NOT request any sub-reviews. "
            "Report all findings directly, even if uncertain."
        )

    prompt = (
        f"Execute the following review dimension.\n\n"
        f"Review prompt: {review_prompt}\n\n"
        f"Target files: {', '.join(target_files)}\n"
        f"Context files: {', '.join(ctx_files) if ctx_files else 'none'}\n\n"
        f"Inspect target files deeply, use context files as needed, and return structured findings.\n\n"
        f"SEVERITY CALIBRATION (use the full range — do NOT default everything to nitpick):\n"
        f"- critical: Bugs, data loss, security holes, crashes, silent corruption. "
        f"Would block merge in any serious project.\n"
        f"- important: Logic errors, missing validation, poor error handling, performance traps, "
        f"API contract violations. Should be fixed before merge.\n"
        f"- suggestion: Design improvements, better abstractions, cleaner patterns, "
        f"edge cases worth handling. Recommended but not blocking.\n"
        f"- nitpick: Style, naming, minor readability tweaks. Truly cosmetic only.\n\n"
        f"A well-calibrated review of real code changes typically produces a MIX of severities. "
        f"If all your findings are the same severity, recalibrate.\n\n"
        f"FORMATTING REQUIREMENTS for finding fields:\n"
        f"- body: Use GitHub Markdown. Bold key terms, use inline `code` for identifiers, "
        f"use code blocks with language hints for code snippets.\n"
        f"- evidence: Quote the specific code or behavior that supports your finding. "
        f"Be precise — include function names, variable names, line references.\n"
        f"- suggestion: Write a concise description of the recommended fix. "
        f"Describe WHAT to change and WHY, as if writing a code comment for a colleague."
        f"{spawn_instruction}"
    )
    result = await router.app.harness(
        prompt,
        schema=_ReviewFindingsResult,
        cwd=repo_path or None,
    )
    parsed = result.parsed if result.parsed else _ReviewFindingsResult()
    sub_review_dicts = []
    if can_spawn and parsed.sub_reviews:
        sub_review_dicts = [
            {
                "reason": sr.reason,
                "review_prompt": sr.review_prompt,
                "target_files": sr.target_files,
                "context_files": sr.context_files,
                "priority": sr.priority,
            }
            for sr in parsed.sub_reviews[:2]
            if sr.review_prompt and sr.target_files
        ]
    return {
        "findings": [finding.model_dump() for finding in parsed.findings],
        "sub_reviews": sub_review_dicts,
        "current_depth": current_depth,
    }


@router.reasoner()
async def cross_ref_phase(findings: list[dict], cross_ref_hints: list[str] | None = None) -> dict:
    import json as _json

    hints = cross_ref_hints or []
    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]

    findings_summary = _json.dumps(
        [
            {
                "title": f.title,
                "severity": f.severity,
                "file_path": f.file_path,
                "dimension_name": f.dimension_name,
                "body": f.body[:200],
            }
            for f in validated_findings[:20]
        ],
        default=str,
    )
    result = await router.app.harness(
        f"Analyze interactions across findings from different review dimensions. "
        f"Identify compound risks, assumption violations, and consistency gaps.\n\n"
        f"Findings:\n{findings_summary}\n\nHints: {hints if hints else 'none'}",
        schema=_CrossRefResult,
    )
    parsed = result.parsed if result.parsed else _CrossRefResult()
    return {"interactions": [interaction.model_dump() for interaction in parsed.interactions]}


@router.reasoner()
async def adversary_phase(findings: list[dict], ai_generated_confidence: float = 0.0) -> dict:
    import json as _json

    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]
    skepticism = "standard"
    if ai_generated_confidence > 0.5:
        skepticism = "high"

    findings_summary = _json.dumps(
        [
            {
                "title": f.title,
                "severity": f.severity,
                "file_path": f.file_path,
                "body": f.body[:200],
                "confidence": f.confidence,
            }
            for f in validated_findings[:20]
        ],
        default=str,
    )
    result = await router.app.harness(
        f"Challenge each finding adversarially. Look for false positives, over-claimed severity, "
        f"and hidden traps that reviewers may have missed.\n\n"
        f"Skepticism mode: {skepticism}\nAI-generated confidence: {ai_generated_confidence}\n\n"
        f"Findings:\n{findings_summary}",
        schema=_AdversaryPhaseResult,
    )
    parsed = result.parsed if result.parsed else _AdversaryPhaseResult()
    return {"results": [item.model_dump() for item in parsed.results]}


@router.reasoner()
async def coverage_gate(anatomy: dict, reviewed_clusters: list[str]) -> dict:
    import json as _json

    anatomy_result = AnatomyResult.model_validate(anatomy)
    cluster_payload = [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "files": cluster.files,
        }
        for cluster in anatomy_result.clusters
    ]

    context = _json.dumps(
        {
            "all_clusters": cluster_payload,
            "reviewed_clusters": reviewed_clusters,
            "risk_surfaces": anatomy_result.risk_surfaces,
        },
        default=str,
    )
    gate = await router.app.ai(
        f"Determine whether review coverage is complete. "
        f"Compare reviewed cluster identifiers against all change clusters. "
        f"If gaps exist, return concise gap_descriptions.\n\n{context}",
        system="Analyze the coverage state and return the structured result.",
        schema=CoverageGate,
    )
    return gate.model_dump()
