from __future__ import annotations

from pydantic import BaseModel, Field

from . import router
from ..blast_radius import compute_blast_radius
from ..diff_engine import cluster_changes, compute_diff_stats, parse_unified_diff
from ..schemas.gates import CoverageGate, IntakeGate
from ..schemas.input import GitHubPRData
from ..schemas.pipeline import (
    AdversaryResult,
    AnatomyResult,
    ChangeCluster,
    CrossRefInteraction,
    DiffStats,
    FileChange,
    IntakeResult,
    ReviewDimension,
    ReviewFinding,
    ReviewPlan,
    SubReviewRequest,
)


class _AnatomySemanticResult(BaseModel):
    pr_narrative: str = ""
    risk_surfaces: list[str] = Field(default_factory=list)
    unrelated_changes: list[str] = Field(default_factory=list)
    intent_gaps: list[str] = Field(default_factory=list)
    context_notes: str = ""


class _SubReviewRequest(BaseModel):
    reason: str = ""
    review_prompt: str = ""
    target_files: list[str] = Field(default_factory=list)
    context_files: list[str] = Field(default_factory=list)
    priority: int = 1


class _ReviewFindingsResult(BaseModel):
    findings: list[ReviewFinding] = Field(default_factory=list)
    sub_reviews: list[_SubReviewRequest] = Field(default_factory=list)


class _CrossRefResult(BaseModel):
    interactions: list[CrossRefInteraction] = Field(default_factory=list)


class _AdversaryPhaseResult(BaseModel):
    results: list[AdversaryResult] = Field(default_factory=list)


def _auto_depth(complexity: str) -> str:
    mapping = {
        "trivial": "quick",
        "standard": "standard",
        "complex": "deep",
        "massive": "deep",
    }
    return mapping.get(complexity, "standard")


def _language_from_path(path: str) -> str:
    ext_map = {
        ".py": "python",
        ".js": "javascript",
        ".jsx": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".rb": "ruby",
        ".php": "php",
        ".swift": "swift",
        ".kt": "kotlin",
        ".cs": "csharp",
        ".cpp": "cpp",
        ".c": "c",
        ".sql": "sql",
        ".html": "html",
        ".css": "css",
        ".md": "markdown",
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".sh": "bash",
    }
    for ext, language in ext_map.items():
        if path.endswith(ext):
            return language
    return ""


def _extract_languages(pr: GitHubPRData) -> list[str]:
    languages = {_language_from_path(changed.path) for changed in pr.changed_files if _language_from_path(changed.path)}
    return sorted(languages)


def _extract_areas(paths: list[str]) -> list[str]:
    area_patterns = {
        "auth": ("auth", "login", "oauth", "permission", "acl"),
        "database": ("db", "database", "migration", "schema", "model"),
        "api": ("api", "endpoint", "route", "controller", "handler"),
        "frontend": ("ui", "component", "view", "page", "css", "tsx", "jsx"),
        "tests": ("test", "spec", "fixture"),
        "ci": (".github", "workflow", "ci", "pipeline"),
        "config": ("config", "settings", ".env", "yaml", "toml", "json"),
        "infra": ("docker", "k8s", "terraform", "helm", "ansible"),
        "security": ("security", "crypto", "token", "jwt", "secret"),
    }
    lowered = [path.lower() for path in paths]
    detected: list[str] = []
    for area, patterns in area_patterns.items():
        if any(any(pattern in path for pattern in patterns) for path in lowered):
            detected.append(area)
    if not detected:
        detected.append("application")
    return detected


def _risk_signals(pr: GitHubPRData, areas_touched: list[str], files_changed: int) -> list[str]:
    signals: list[str] = []
    if "security" in areas_touched or "auth" in areas_touched:
        signals.append("touches authentication or security-sensitive paths")
    if "database" in areas_touched:
        signals.append("modifies data model or schema-affecting code")
    if "api" in areas_touched:
        signals.append("changes API surface or request/response behavior")
    if files_changed >= 25:
        signals.append("large change footprint across many files")
    if any(path.endswith((".yml", ".yaml", ".toml", ".json")) for path in (cf.path for cf in pr.changed_files)):
        signals.append("includes configuration changes")
    if any("test" in cf.path.lower() for cf in pr.changed_files):
        signals.append("test behavior updated")
    return signals


def _ai_generated_confidence(pr: GitHubPRData) -> float:
    signals = 0
    evidence = 0
    text_blobs = [pr.title, pr.description, *pr.commit_messages]
    patterns = (
        "generated by",
        "co-authored-by: claude",
        "co-authored-by: gpt",
        "ai-assisted",
        "autogenerated",
        "chatgpt",
        "copilot",
        "claude",
        "llm",
    )
    for blob in text_blobs:
        if not blob:
            continue
        evidence += 1
        lower = blob.lower()
        if any(pattern in lower for pattern in patterns):
            signals += 1
    if evidence == 0:
        return 0.0
    return min(1.0, signals / evidence)


def _pr_summary(pr: GitHubPRData) -> str:
    description = (pr.description or "").strip()
    if description:
        return description
    return f"{pr.title}. Files changed: {len(pr.changed_files)}."


def _file_changes_from_metadata(pr: GitHubPRData) -> list[FileChange]:
    return [
        FileChange(
            path=changed.path,
            status=changed.status,
            language=_language_from_path(changed.path),
            lines_added=changed.additions,
            lines_removed=changed.deletions,
            hunks=[],
        )
        for changed in pr.changed_files
    ]


def _cluster_descriptions(clusters: list[ChangeCluster]) -> list[dict[str, object]]:
    return [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "primary_language": cluster.primary_language,
            "files": cluster.files,
        }
        for cluster in clusters
    ]


@router.reasoner()
async def intake_phase(pr_data: dict, depth: str = "standard") -> dict:
    pr = GitHubPRData.model_validate(pr_data)
    files_changed = len(pr.changed_files)
    languages = _extract_languages(pr)
    import json as _json

    ai_input = _json.dumps(
        {
            "title": pr.title,
            "description": (pr.description or "")[:500],
            "labels": pr.labels,
            "author": pr.author,
            "files_changed": files_changed,
            "languages": languages,
            "commit_messages": pr.commit_messages[:5],
        },
        default=str,
    )

    gate_result = await router.app.ai(
        f"Classify this pull request from metadata and diff footprint.\n\n{ai_input}",
        system="Return pr_type, complexity, and confident only. Use the provided schema.",
        schema=IntakeGate,
    )

    if gate_result.confident:
        paths = [changed.path for changed in pr.changed_files]
        areas_touched = _extract_areas(paths)
        intake_result = IntakeResult(
            pr_type=gate_result.pr_type,
            complexity=gate_result.complexity,
            languages=languages,
            areas_touched=areas_touched,
            risk_signals=_risk_signals(pr, areas_touched, files_changed),
            ai_generated=_ai_generated_confidence(pr),
            review_depth=depth if depth != "auto" else _auto_depth(gate_result.complexity),
            pr_summary=_pr_summary(pr),
        )
        return intake_result.model_dump()

    fallback_input = _json.dumps(
        {
            "pr_title": pr.title,
            "description": (pr.description or "")[:1000],
            "requested_depth": depth,
            "languages": languages,
            "files_changed": files_changed,
        },
        default=str,
    )
    fallback_result = await router.app.harness(
        f"Classify this pull request for a multi-agent review pipeline. "
        f"Downstream reviewers will rely on your classification to decide review depth "
        f"and focus areas, so accuracy matters more than speed.\n\n"
        f"Determine: PR type (feature/bugfix/refactor/docs/config/dependency/test), "
        f"complexity (trivial/standard/complex/massive), areas touched, risk signals, "
        f"AI-generation confidence, and write a technical PR summary that captures the "
        f"actual substance of the change (not just the PR title restated).\n\n{fallback_input}",
        schema=IntakeResult,
    )
    return fallback_result.parsed.model_dump() if fallback_result.parsed else {}


@router.reasoner()
async def anatomy_phase(pr_data: dict, intake: dict, repo_path: str = "") -> dict:
    import json as _json

    pr = GitHubPRData.model_validate(pr_data)
    intake_result = IntakeResult.model_validate(intake)

    files = parse_unified_diff(pr.diff)
    if not files:
        files = _file_changes_from_metadata(pr)

    stats = compute_diff_stats(files)
    clusters = cluster_changes(files)
    changed_paths = [file.path for file in files]
    blast_radius = compute_blast_radius(changed_paths, repo_path)

    context = _json.dumps(
        {
            "intake": {
                "pr_type": intake_result.pr_type,
                "complexity": intake_result.complexity,
                "pr_summary": intake_result.pr_summary,
            },
            "pr_metadata": {"title": pr.title, "description": (pr.description or "")[:500], "labels": pr.labels},
            "clusters": _cluster_descriptions(clusters),
            "stats": stats.model_dump(),
            "blast_radius_count": len(blast_radius),
            "files_changed": [
                {"path": f.path, "status": f.status, "lines_added": f.lines_added, "lines_removed": f.lines_removed}
                for f in files[:30]
            ],
        },
        default=str,
    )
    semantic = await router.app.harness(
        f"You are a senior engineer performing structural analysis of a pull request before "
        f"review dimensions are assigned. Your job is NOT to find bugs yet — it is to deeply "
        f"understand WHAT changed, WHY it changed, and WHERE the risk surfaces are.\n\n"
        f"Think like an architect reviewing a change set:\n\n"
        f"1. **PR Narrative**: Write a clear technical narrative of what this PR actually does "
        f"(not what the PR description says — what the CODE says). Trace the change from "
        f"entry point to effect. If the PR replaces one mechanism with another, describe both "
        f"the old and new mechanisms and where they differ.\n\n"
        f"2. **Risk Surfaces**: Identify areas where this change could break things that are "
        f"NOT obvious from the diff alone. Think about:\n"
        f"   - Callers of changed functions/methods that might pass arguments differently\n"
        f"   - Implicit contracts (ordering, timing, state) that the change might violate\n"
        f"   - Error paths — if the old code handled errors one way, does the new code preserve that?\n"
        f"   - Concurrency: thread safety, shared state, decorator-injected arguments\n"
        f"   - API boundaries: do callers still get what they expect?\n"
        f"   - Configuration/defaults that changed (especially security-sensitive ones)\n\n"
        f"3. **Unrelated Changes**: Flag anything that doesn't belong in this PR's stated intent.\n\n"
        f"4. **Intent Gaps**: Where does the code diverge from what the PR description promises? "
        f"Where is the PR description silent about something the code actually does?\n\n"
        f"Be specific. Name files, functions, and line ranges. A vague risk surface is useless.\n\n"
        f"{context}",
        schema=_AnatomySemanticResult,
        cwd=repo_path or None,
    )

    parsed = semantic.parsed if semantic.parsed else _AnatomySemanticResult()
    anatomy_result = AnatomyResult(
        files=files,
        clusters=clusters,
        blast_radius=blast_radius,
        dependency_graph={},
        stats=stats,
        pr_narrative=parsed.pr_narrative,
        risk_surfaces=parsed.risk_surfaces,
        unrelated_changes=parsed.unrelated_changes,
        intent_gaps=parsed.intent_gaps,
        context_notes=parsed.context_notes,
    )
    return anatomy_result.model_dump()


@router.reasoner()
async def planning_phase(intake: dict, anatomy: dict, depth: str = "standard", hints: list[str] | None = None) -> dict:
    import json as _json

    intake_result = IntakeResult.model_validate(intake)
    anatomy_result = AnatomyResult.model_validate(anatomy)
    planner_hints = hints or []

    context = _json.dumps(
        {
            "intake": {
                "pr_type": intake_result.pr_type,
                "complexity": intake_result.complexity,
                "pr_summary": intake_result.pr_summary,
                "areas_touched": intake_result.areas_touched,
                "risk_signals": intake_result.risk_signals,
            },
            "clusters": _cluster_descriptions(anatomy_result.clusters),
            "risk_surfaces": anatomy_result.risk_surfaces,
            "pr_narrative": anatomy_result.pr_narrative,
            "depth": depth,
            "hints": planner_hints,
            "file_paths": [f.path for f in anatomy_result.files[:30]],
        },
        default=str,
    )
    plan_result = await router.app.harness(
        f"You are a principal engineer designing a review strategy for a pull request. "
        f"Your job is to decompose this PR into review DIMENSIONS — each one a focused, "
        f"independently-executable investigation that another senior engineer will carry out.\n\n"
        f"DO NOT use generic templates like 'security review' or 'performance review'. "
        f"Every dimension must be SPECIFIC to what THIS PR actually changes.\n\n"
        f"## How to Think About Dimensions\n\n"
        f"A dimension is NOT 'check file X for bugs'. A dimension is a specific QUESTION about "
        f"the change that requires reading code to answer. Good dimensions:\n\n"
        f"- 'Does the migration from library A to library B preserve error semantics?' "
        f"(target: the wrapper functions; context: the callers)\n"
        f"- 'Are all callers of method X updated to match its new signature?' "
        f"(target: the callers; context: the method definition)\n"
        f"- 'Does the new default value for config Y break existing deployments?' "
        f"(target: where Y is consumed; context: where Y is defined and documented)\n"
        f"- 'Can the refactored data flow produce states that the old flow could not?' "
        f"(target: state transitions; context: consumers of that state)\n\n"
        f"Bad dimensions: 'Review security', 'Check for bugs', 'Validate tests'\n\n"
        f"## Dimension Categories to Consider\n\n"
        f"Not all will apply — generate ONLY what matters for THIS PR:\n\n"
        f"1. **Behavioral Equivalence**: When code is refactored or a dependency is swapped, "
        f"does the new code behave identically in all paths? Edge cases, error handling, "
        f"return types, side effects, timing.\n\n"
        f"2. **Contract Preservation**: Are function signatures, decorator behaviors, "
        f"serialization formats, and API responses preserved? When a decorator adds an "
        f"implicit parameter, are all call sites (direct AND indirect) updated?\n\n"
        f"3. **Cross-Boundary Consistency**: Changes in module A may violate assumptions "
        f"in module B. Look for shared types, constants, configs, or patterns that appear "
        f"in both changed and unchanged files.\n\n"
        f"4. **Error Propagation & Recovery**: Follow every error path. Does the new code "
        f"catch the same exceptions? Raise the same error types? Preserve error codes? "
        f"Avoid swallowing errors that the old code surfaced?\n\n"
        f"5. **State & Concurrency**: Thread-local storage, shared handles, connection "
        f"lifecycle, resource cleanup. Does the change introduce shared mutable state, "
        f"or change who owns a resource?\n\n"
        f"6. **Data Integrity & Migration**: Schema changes, default value changes, "
        f"format changes. Can old data be read by new code? Can new data be read by "
        f"rollback code?\n\n"
        f"7. **Architectural Coherence**: Does this change follow or violate the codebase's "
        f"established patterns? Does it introduce a new pattern where one already exists? "
        f"Does it create technical debt or resolve it?\n\n"
        f"## Review Prompt Craft\n\n"
        f"Each dimension's `review_prompt` will be given to another engineer who will read "
        f"the actual code. Make it a COMPLETE briefing:\n"
        f"- State exactly what to investigate\n"
        f"- Explain what 'correct' looks like\n"
        f"- Point out what subtle failures would look like\n"
        f"- Mention specific functions, classes, or patterns to trace\n\n"
        f"## Cross-Reference Hints\n\n"
        f"Identify specific pairs or groups of findings that could interact. "
        f"Example: 'If dimension A finds that error types changed, AND dimension B finds "
        f"callers that catch specific error types, those interact.'\n\n"
        f"## Output Requirements\n\n"
        f"- Prioritize dimensions by risk (highest first)\n"
        f"- Each dimension has: target_files (to inspect) and context_files (for reference)\n"
        f"- Depth '{depth}' means: quick=2-3 dimensions, standard=3-5, deep=5-8, thorough=6-10\n"
        f"- If the PR has a narrow scope, fewer dimensions is BETTER than padding with fluff\n\n"
        f"{context}",
        schema=ReviewPlan,
    )
    return plan_result.parsed.model_dump() if plan_result.parsed else {"dimensions": [], "cross_ref_hints": []}


@router.reasoner()
async def review_dimension(
    review_prompt: str,
    target_files: list[str],
    context_files: list[str] | None = None,
    repo_path: str = "",
    current_depth: int = 0,
    max_depth: int = 2,
) -> dict:
    ctx_files = context_files or []
    can_spawn = current_depth < max_depth

    spawn_instruction = ""
    if can_spawn:
        spawn_instruction = (
            "\n\nSUB-REVIEW SPAWNING: You may request deeper sub-reviews for areas that need "
            "specialized investigation beyond your current scope. Only request a sub-review when:\n"
            "- You found a complex issue that requires reading additional files not in your target list\n"
            "- A finding reveals a pattern that may repeat across other files\n"
            "- You suspect a security/correctness issue but lack context to confirm it\n"
            f"Current depth: {current_depth}/{max_depth}. "
            f"You have {max_depth - current_depth} level(s) of sub-review remaining. "
            "Do NOT request sub-reviews for trivial issues or things you can resolve yourself. "
            "Maximum 2 sub-reviews per dimension."
        )
    else:
        spawn_instruction = (
            "\n\nYou are at maximum review depth. Do NOT request any sub-reviews. "
            "Report all findings directly, even if uncertain."
        )

    prompt = (
        f"You are a senior engineer performing a focused code review. You have been assigned "
        f"a specific review dimension with a clear investigation question.\n\n"
        f"## Your Assignment\n\n"
        f"{review_prompt}\n\n"
        f"**Target files** (read and analyze these): {', '.join(target_files)}\n"
        f"**Context files** (reference as needed): {', '.join(ctx_files) if ctx_files else 'none'}\n\n"
        f"## How to Review\n\n"
        f"Do NOT just scan for surface-level issues. Think deeply about what this code DOES:\n\n"
        f"1. **Read the target files thoroughly.** Understand the control flow, data flow, "
        f"and error paths. Pay attention to what happens at boundaries — function entry/exit, "
        f"exception handlers, early returns, decorator effects.\n\n"
        f"2. **Trace implications.** If a function signature changed, who calls it? "
        f"If a default value changed, where is it consumed? If an import was added or removed, "
        f"what depended on it? Read context files to verify.\n\n"
        f"3. **Check behavioral equivalence.** If code was refactored or a library was swapped, "
        f"does the new version handle ALL the same cases? Edge cases matter: empty inputs, "
        f"None values, concurrent access, error conditions, type mismatches.\n\n"
        f"4. **Verify contracts.** Are return types preserved? Are exception types consistent? "
        f"Do decorators inject parameters that callers might not account for? "
        f"Are there implicit ordering dependencies?\n\n"
        f"5. **Think about what's NOT in the diff.** The most dangerous bugs are in code "
        f"that WASN'T changed but SHOULD have been. If a method's signature changed, "
        f"every caller needs updating. If an enum added a variant, every switch/match "
        f"needs the new case.\n\n"
        f"## Severity Calibration\n\n"
        f"Use the FULL severity range. A well-calibrated review has a MIX:\n\n"
        f"- **critical**: Runtime crashes, data corruption, security vulnerabilities, "
        f"silent logic errors that produce wrong results. The code WILL fail in production. "
        f"You must be able to describe the EXACT failure scenario — 'X calls Y with Z, "
        f"which causes W'. Vague concerns are not critical.\n"
        f"- **important**: Missing error handling, validation gaps, API contract violations, "
        f"race conditions under realistic load, performance traps with specific data sizes. "
        f"The code CAN fail under known conditions.\n"
        f"- **suggestion**: Better design patterns, improved abstractions, edge cases worth "
        f"handling, test coverage gaps for specific scenarios. The code works but could be "
        f"more robust.\n"
        f"- **nitpick**: Naming, style, readability, documentation. Truly cosmetic.\n\n"
        f"If you're unsure whether something is critical or important, provide your reasoning "
        f"in the `body` field and let the confidence score reflect your uncertainty.\n\n"
        f"## Output Quality\n\n"
        f"For each finding, use proper GitHub Markdown:\n"
        f"- **body**: Explain the issue clearly. Use `inline code` for identifiers. "
        f"Use code blocks with language hints for snippets. Bold key terms. "
        f"Explain WHY this is a problem, not just WHAT is wrong.\n"
        f"- **evidence**: Quote the EXACT code or trace the EXACT call path that demonstrates "
        f"the issue. Include function names, parameter bindings, and return values. "
        f"'Step 1: X calls Y with arg=Z. Step 2: Y binds Z to parameter W. Step 3: W.foo() "
        f"fails because Z is a list, not a TLS object.'\n"
        f"- **suggestion**: Describe the fix concisely. What to change, where, and why. "
        f"If there are multiple valid approaches, mention the tradeoffs.\n"
        f"- **file_path**: Full path from the repository root.\n"
        f"- **line_start**: The specific line where the issue manifests. Be precise.\n\n"
        f"Do NOT produce findings you aren't confident about just to fill a quota. "
        f"Three well-evidenced findings are worth more than ten vague ones."
        f"{spawn_instruction}"
    )
    result = await router.app.harness(
        prompt,
        schema=_ReviewFindingsResult,
        cwd=repo_path or None,
    )
    parsed = result.parsed if result.parsed else _ReviewFindingsResult()
    sub_review_dicts = []
    if can_spawn and parsed.sub_reviews:
        sub_review_dicts = [
            {
                "reason": sr.reason,
                "review_prompt": sr.review_prompt,
                "target_files": sr.target_files,
                "context_files": sr.context_files,
                "priority": sr.priority,
            }
            for sr in parsed.sub_reviews[:2]
            if sr.review_prompt and sr.target_files
        ]
    return {
        "findings": [finding.model_dump() for finding in parsed.findings],
        "sub_reviews": sub_review_dicts,
        "current_depth": current_depth,
    }


@router.reasoner()
async def cross_ref_phase(findings: list[dict], cross_ref_hints: list[str] | None = None) -> dict:
    import json as _json

    hints = cross_ref_hints or []
    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]

    findings_summary = _json.dumps(
        [
            {
                "title": f.title,
                "severity": f.severity,
                "file_path": f.file_path,
                "dimension_name": f.dimension_name,
                "body": f.body[:200],
            }
            for f in validated_findings[:20]
        ],
        default=str,
    )
    result = await router.app.harness(
        f"You are analyzing the INTERACTIONS between findings from different review dimensions. "
        f"Individual reviewers examined separate aspects of the PR. Your job is to find where "
        f"their findings COMBINE to create risks that neither reviewer saw alone.\n\n"
        f"## What to Look For\n\n"
        f"1. **Compound Failures**: Finding A says 'function X changed its error type' and "
        f"Finding B says 'caller Y catches the old error type' → together, errors are silently "
        f"swallowed.\n\n"
        f"2. **Contradictory Assumptions**: One reviewer assumes a lock is held, another's "
        f"finding shows the lock was removed. One assumes a value is non-null, another's "
        f"finding shows it can be null now.\n\n"
        f"3. **Cascade Effects**: A 'suggestion'-level finding in module A becomes 'critical' "
        f"when combined with an 'important' finding in module B, because together they create "
        f"a data corruption path.\n\n"
        f"4. **Consistency Gaps**: One part of the codebase was updated to a new pattern, "
        f"but another part (found by a different reviewer) still uses the old pattern.\n\n"
        f"5. **Hidden Dependencies**: Findings in separate files that share an implicit "
        f"contract (same config key, same database table, same API response shape).\n\n"
        f"Only report interactions you can TRACE through specific findings. "
        f"Do not speculate about interactions that 'might' exist.\n\n"
        f"Findings:\n{findings_summary}\n\nReview hints: {hints if hints else 'none'}",
        schema=_CrossRefResult,
    )
    parsed = result.parsed if result.parsed else _CrossRefResult()
    return {"interactions": [interaction.model_dump() for interaction in parsed.interactions]}


@router.reasoner()
async def adversary_phase(findings: list[dict], ai_generated_confidence: float = 0.0) -> dict:
    import json as _json

    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]
    skepticism = "standard"
    if ai_generated_confidence > 0.5:
        skepticism = "high"

    findings_summary = _json.dumps(
        [
            {
                "title": f.title,
                "severity": f.severity,
                "file_path": f.file_path,
                "body": f.body[:200],
                "confidence": f.confidence,
            }
            for f in validated_findings[:20]
        ],
        default=str,
    )
    result = await router.app.harness(
        f"You are the adversarial reviewer — your job is to CHALLENGE every finding and "
        f"determine whether it's real or a false positive. You are skeptical by default.\n\n"
        f"## For Each Finding, Determine:\n\n"
        f"1. **Is the failure scenario actually reachable?** Trace the call path. "
        f"Can the described inputs actually reach this code? Are there guards upstream "
        f"that prevent the bad state?\n\n"
        f"2. **Is the severity correct?** A 'critical' finding must have a concrete crash "
        f"or corruption scenario. If it's speculative ('could potentially cause issues'), "
        f"it's not critical. Downgrade or challenge it.\n\n"
        f"3. **Is the evidence accurate?** Does the code actually do what the reviewer claims? "
        f"Check: did the reviewer misread a decorator's behavior? Did they assume a function "
        f"is called directly when it's actually dispatched through a framework?\n\n"
        f"4. **Is there a hidden trap the reviewer MISSED?** Sometimes the reviewer found "
        f"a real issue but missed the WORSE version of it, or missed that the fix they "
        f"suggested would break something else.\n\n"
        f"## Verdicts\n\n"
        f"- **confirmed**: The finding is real. The evidence checks out. The severity is "
        f"appropriate. Briefly explain why you're convinced.\n"
        f"- **challenged**: The finding is a false positive, the severity is wrong, or the "
        f"evidence doesn't hold up. Explain specifically what's wrong with the reviewer's "
        f"reasoning.\n"
        f"- **escalated**: The reviewer found something real but UNDERESTIMATED the severity "
        f"or scope. Explain what they missed.\n\n"
        f"Skepticism mode: {skepticism}\n"
        f"AI-generated confidence: {ai_generated_confidence}\n"
        f"{'(Higher AI confidence → be MORE skeptical of trivial findings)' if ai_generated_confidence > 0.5 else ''}\n\n"
        f"Findings:\n{findings_summary}",
        schema=_AdversaryPhaseResult,
    )
    parsed = result.parsed if result.parsed else _AdversaryPhaseResult()
    return {"results": [item.model_dump() for item in parsed.results]}


@router.reasoner()
async def coverage_gate(anatomy: dict, reviewed_clusters: list[str]) -> dict:
    import json as _json

    anatomy_result = AnatomyResult.model_validate(anatomy)
    cluster_payload = [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "files": cluster.files,
        }
        for cluster in anatomy_result.clusters
    ]

    context = _json.dumps(
        {
            "all_clusters": cluster_payload,
            "reviewed_clusters": reviewed_clusters,
            "risk_surfaces": anatomy_result.risk_surfaces,
        },
        default=str,
    )
    gate = await router.app.ai(
        f"Determine whether review coverage is complete. "
        f"Compare reviewed cluster identifiers against all change clusters. "
        f"If gaps exist, return concise gap_descriptions.\n\n{context}",
        system="Analyze the coverage state and return the structured result.",
        schema=CoverageGate,
    )
    return gate.model_dump()
