from __future__ import annotations

from pydantic import BaseModel, Field

from . import router
from ..blast_radius import compute_blast_radius
from ..diff_engine import cluster_changes, compute_diff_stats, parse_unified_diff
from ..schemas.gates import CoverageGate, IntakeGate
from ..schemas.input import GitHubPRData
from ..schemas.pipeline import (
    AdversaryResult,
    AnatomyResult,
    ChangeCluster,
    CrossRefInteraction,
    DiffStats,
    FileChange,
    IntakeResult,
    ReviewDimension,
    ReviewFinding,
    ReviewPlan,
)


class _AnatomySemanticResult(BaseModel):
    pr_narrative: str
    risk_surfaces: list[str] = Field(default_factory=list)
    unrelated_changes: list[str] = Field(default_factory=list)
    intent_gaps: list[str] = Field(default_factory=list)
    context_notes: str = ""


class _ReviewFindingsResult(BaseModel):
    findings: list[ReviewFinding] = Field(default_factory=list)


class _CrossRefResult(BaseModel):
    interactions: list[CrossRefInteraction] = Field(default_factory=list)


class _AdversaryPhaseResult(BaseModel):
    results: list[AdversaryResult] = Field(default_factory=list)


def _auto_depth(complexity: str) -> str:
    mapping = {
        "trivial": "quick",
        "standard": "standard",
        "complex": "deep",
        "massive": "deep",
    }
    return mapping.get(complexity, "standard")


def _language_from_path(path: str) -> str:
    ext_map = {
        ".py": "python",
        ".js": "javascript",
        ".jsx": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".rb": "ruby",
        ".php": "php",
        ".swift": "swift",
        ".kt": "kotlin",
        ".cs": "csharp",
        ".cpp": "cpp",
        ".c": "c",
        ".sql": "sql",
        ".html": "html",
        ".css": "css",
        ".md": "markdown",
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".sh": "bash",
    }
    for ext, language in ext_map.items():
        if path.endswith(ext):
            return language
    return ""


def _extract_languages(pr: GitHubPRData) -> list[str]:
    languages = {_language_from_path(changed.path) for changed in pr.changed_files if _language_from_path(changed.path)}
    return sorted(languages)


def _extract_areas(paths: list[str]) -> list[str]:
    area_patterns = {
        "auth": ("auth", "login", "oauth", "permission", "acl"),
        "database": ("db", "database", "migration", "schema", "model"),
        "api": ("api", "endpoint", "route", "controller", "handler"),
        "frontend": ("ui", "component", "view", "page", "css", "tsx", "jsx"),
        "tests": ("test", "spec", "fixture"),
        "ci": (".github", "workflow", "ci", "pipeline"),
        "config": ("config", "settings", ".env", "yaml", "toml", "json"),
        "infra": ("docker", "k8s", "terraform", "helm", "ansible"),
        "security": ("security", "crypto", "token", "jwt", "secret"),
    }
    lowered = [path.lower() for path in paths]
    detected: list[str] = []
    for area, patterns in area_patterns.items():
        if any(any(pattern in path for pattern in patterns) for path in lowered):
            detected.append(area)
    if not detected:
        detected.append("application")
    return detected


def _risk_signals(pr: GitHubPRData, areas_touched: list[str], files_changed: int) -> list[str]:
    signals: list[str] = []
    if "security" in areas_touched or "auth" in areas_touched:
        signals.append("touches authentication or security-sensitive paths")
    if "database" in areas_touched:
        signals.append("modifies data model or schema-affecting code")
    if "api" in areas_touched:
        signals.append("changes API surface or request/response behavior")
    if files_changed >= 25:
        signals.append("large change footprint across many files")
    if any(path.endswith((".yml", ".yaml", ".toml", ".json")) for path in (cf.path for cf in pr.changed_files)):
        signals.append("includes configuration changes")
    if any("test" in cf.path.lower() for cf in pr.changed_files):
        signals.append("test behavior updated")
    return signals


def _ai_generated_confidence(pr: GitHubPRData) -> float:
    signals = 0
    evidence = 0
    text_blobs = [pr.title, pr.description, *pr.commit_messages]
    patterns = (
        "generated by",
        "co-authored-by: claude",
        "co-authored-by: gpt",
        "ai-assisted",
        "autogenerated",
        "chatgpt",
        "copilot",
        "claude",
        "llm",
    )
    for blob in text_blobs:
        if not blob:
            continue
        evidence += 1
        lower = blob.lower()
        if any(pattern in lower for pattern in patterns):
            signals += 1
    if evidence == 0:
        return 0.0
    return min(1.0, signals / evidence)


def _pr_summary(pr: GitHubPRData) -> str:
    description = (pr.description or "").strip()
    if description:
        return description
    return f"{pr.title}. Files changed: {len(pr.changed_files)}."


def _file_changes_from_metadata(pr: GitHubPRData) -> list[FileChange]:
    return [
        FileChange(
            path=changed.path,
            status=changed.status,
            language=_language_from_path(changed.path),
            lines_added=changed.additions,
            lines_removed=changed.deletions,
            hunks=[],
        )
        for changed in pr.changed_files
    ]


def _cluster_descriptions(clusters: list[ChangeCluster]) -> list[dict[str, object]]:
    return [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "primary_language": cluster.primary_language,
            "files": cluster.files,
        }
        for cluster in clusters
    ]


@router.reasoner()
async def intake_phase(pr_data: dict, depth: str = "standard") -> dict:
    pr = GitHubPRData.model_validate(pr_data)
    files_changed = len(pr.changed_files)
    languages = _extract_languages(pr)

    gate_result = await router.app.ai(
        prompt=(
            "Classify this pull request from metadata and diff footprint. "
            "Return pr_type, complexity, and confident only."
        ),
        input={
            "title": pr.title,
            "description": pr.description,
            "labels": pr.labels,
            "author": pr.author,
            "files_changed": files_changed,
            "languages": languages,
            "commit_messages": pr.commit_messages,
        },
        schema=IntakeGate,
    )

    if gate_result.confident:
        paths = [changed.path for changed in pr.changed_files]
        areas_touched = _extract_areas(paths)
        intake_result = IntakeResult(
            pr_type=gate_result.pr_type,
            complexity=gate_result.complexity,
            languages=languages,
            areas_touched=areas_touched,
            risk_signals=_risk_signals(pr, areas_touched, files_changed),
            ai_generated=_ai_generated_confidence(pr),
            review_depth=depth if depth != "auto" else _auto_depth(gate_result.complexity),
            pr_summary=_pr_summary(pr),
        )
        return intake_result.model_dump()

    fallback_result = await router.app.harness(
        prompt=(
            "Perform deep intake classification for this pull request. "
            "Infer PR type, complexity, touched areas, risk signals, AI-generation confidence, "
            "and an accurate short PR summary for downstream reviewers."
        ),
        input={
            "pr_data": pr.model_dump(),
            "requested_depth": depth,
            "language_hints": languages,
        },
        schema=IntakeResult,
    )
    return fallback_result.model_dump()


@router.reasoner()
async def anatomy_phase(pr_data: dict, intake: dict, repo_path: str = "") -> dict:
    pr = GitHubPRData.model_validate(pr_data)
    intake_result = IntakeResult.model_validate(intake)

    files = parse_unified_diff(pr.diff)
    if not files:
        files = _file_changes_from_metadata(pr)

    stats = compute_diff_stats(files)
    clusters = cluster_changes(files)
    changed_paths = [file.path for file in files]
    blast_radius = compute_blast_radius(changed_paths, repo_path)

    semantic = await router.app.harness(
        prompt=(
            "Analyze the pull request semantically. Explain what changed and why, identify risk surfaces, "
            "call out unrelated changes, and detect intent gaps between PR description and actual diff."
        ),
        input={
            "intake": intake_result.model_dump(),
            "pr_metadata": {
                "title": pr.title,
                "description": pr.description,
                "labels": pr.labels,
                "commit_messages": pr.commit_messages,
            },
            "files": [file.model_dump() for file in files],
            "clusters": _cluster_descriptions(clusters),
            "stats": stats.model_dump(),
            "blast_radius": blast_radius,
        },
        schema=_AnatomySemanticResult,
        cwd=repo_path,
    )

    anatomy_result = AnatomyResult(
        files=files,
        clusters=clusters,
        blast_radius=blast_radius,
        dependency_graph={},
        stats=stats,
        pr_narrative=semantic.pr_narrative,
        risk_surfaces=semantic.risk_surfaces,
        unrelated_changes=semantic.unrelated_changes,
        intent_gaps=semantic.intent_gaps,
        context_notes=semantic.context_notes,
    )
    return anatomy_result.model_dump()


@router.reasoner()
async def planning_phase(intake: dict, anatomy: dict, depth: str = "standard", hints: list[str] | None = None) -> dict:
    intake_result = IntakeResult.model_validate(intake)
    anatomy_result = AnatomyResult.model_validate(anatomy)
    planner_hints = hints or []

    plan = await router.app.harness(
        prompt=(
            "Create a dynamic review plan for this PR. Do not use fixed reviewer templates. "
            "Generate review dimensions based on intake and anatomy, with clear target files and context files. "
            "Each dimension must include a concrete review_prompt that another reviewer can execute directly. "
            "Balance depth with the requested review depth and prioritize highest-risk dimensions first."
        ),
        input={
            "intake": intake_result.model_dump(),
            "anatomy": anatomy_result.model_dump(),
            "depth": depth,
            "hints": planner_hints,
        },
        schema=ReviewPlan,
    )
    return plan.model_dump()


@router.reasoner()
async def review_dimension(
    review_prompt: str,
    target_files: list[str],
    context_files: list[str] | None = None,
    repo_path: str = "",
) -> dict:
    context = context_files or []
    result = await router.app.harness(
        prompt=(
            "Execute one review dimension using the provided review prompt. "
            "Inspect target files deeply, use context files as needed, and return structured findings only."
        ),
        input={
            "review_prompt": review_prompt,
            "target_files": target_files,
            "context_files": context,
        },
        schema=_ReviewFindingsResult,
        cwd=repo_path,
    )
    return {"findings": [finding.model_dump() for finding in result.findings]}


@router.reasoner()
async def cross_ref_phase(findings: list[dict], cross_ref_hints: list[str] | None = None) -> dict:
    hints = cross_ref_hints or []
    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]

    result = await router.app.harness(
        prompt=(
            "Analyze interactions across findings from different review dimensions. "
            "Identify compound risks, assumption violations, and consistency gaps."
        ),
        input={
            "findings": [finding.model_dump() for finding in validated_findings],
            "cross_ref_hints": hints,
        },
        schema=_CrossRefResult,
    )
    return {"interactions": [interaction.model_dump() for interaction in result.interactions]}


@router.reasoner()
async def adversary_phase(findings: list[dict], ai_generated_confidence: float = 0.0) -> dict:
    validated_findings = [ReviewFinding.model_validate(finding) for finding in findings]
    skepticism = "standard"
    if ai_generated_confidence > 0.5:
        skepticism = "high"

    result = await router.app.harness(
        prompt=(
            "Challenge each finding adversarially. Look for false positives, over-claimed severity, "
            "and hidden traps that reviewers may have missed."
        ),
        input={
            "findings": [finding.model_dump() for finding in validated_findings],
            "ai_generated_confidence": ai_generated_confidence,
            "skepticism_mode": skepticism,
        },
        schema=_AdversaryPhaseResult,
    )
    return {"results": [item.model_dump() for item in result.results]}


@router.reasoner()
async def coverage_gate(anatomy: dict, reviewed_clusters: list[str]) -> dict:
    anatomy_result = AnatomyResult.model_validate(anatomy)
    cluster_payload = [
        {
            "id": cluster.id,
            "name": cluster.name,
            "description": cluster.description,
            "files": cluster.files,
        }
        for cluster in anatomy_result.clusters
    ]

    gate = await router.app.ai(
        prompt=(
            "Determine whether review coverage is complete. "
            "Compare reviewed cluster identifiers against all change clusters. "
            "If gaps exist, return concise gap_descriptions."
        ),
        input={
            "all_clusters": cluster_payload,
            "reviewed_clusters": reviewed_clusters,
            "risk_surfaces": anatomy_result.risk_surfaces,
        },
        schema=CoverageGate,
    )
    return gate.model_dump()
